name: cwm
services:
  mongodb-primary:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.5
    restart: on-failure
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - BITNAMI_DEBUG=true
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"

  cis-backend:
    image: ghcr.io/eed-web-application/core-inventory-system:latest
    restart: on-failure
    environment:
      - CIS_MONGODB_URI=mongodb://cis:cis@mongodb-primary:27017/cis?authSource=cis
      - CIS_ADMIN_MONGODB_URI=mongodb://admin:admin@mongodb-primary:27017/?authSource=admin
      - WAIT_LOGGER_LEVEL=debug
      - WAIT_TIMEOUT=90
      - WAIT_HOSTS=mongodb-primary:27017
      - SPRING_PROFILES_ACTIVE=test,manage-root-user,init-demo-database
      - CIS_ROOT_AUTHENTICATION_TOKEN_JSON=[{\"name\":\"root-token-1\",\"expiration\":\"2024-12-31\"}]
    ports:
      - "8081:8080"

#
#  minio:
#    image: minio/minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      - MINIO_ROOT_USER=minio
#      - MINIO_ROOT_PASSWORD=minio123
#    command: server --console-address ":9001" /data
#
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: docker.io/bitnami/kafka:3.5
#    ports:
#      - "9092:9092"
#      - '9094:9094'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_KRAFT_BROKER_ID=1
#      - KAFKA_CFG_NODE_ID = 1
#      - KAFKA_ENABLE_KRAFT=NO
#      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#    depends_on:
#      - zookeeper